### ISSUE TITLE
move this repo over to FLIF-hub ?

### ISSUE THREAD

**Issue by jonsneyers** [matthiaskrgr/flifcrush#11]
Just a suggestion -- I think it would help to give somewhat more visibility to this nice project.

**Comment by matthiaskrgr** [comment]
Hmm.
I see this mostly as an experimental toy. I was trying to expand my python knowledge but was also curious what I was able to tease out of flif. 
An implementation in C, somewhat integrated into FLIF (maybe as plugin or using the lib or something like that) which decodes the input image once (currently flifcrush / flif needs to decode the image every time a new parameter configuration is tried out) and then perhaps modifies the tree directly (instead of trying different input parameters which might not always result in a different tree?) might be a lot faster.
Depending on the image size (px), flifcrush can take several hours on a big image (though I have some rough ideas how to cut that down, or make implement different optimization levels).

I'm not objecting moving this over to FLIF-hub/flifcrush, feel free to fork it.
I could continue making small steps in development here and merge progress over to the FLIF-hub repo every few days, so that the FLIF-hub fork is a bit more stable and does not get buggy/brainfarty commits that I pushed at 2 in the morning/night ;)

**Comment by jonsneyers** [comment]
The way I see it, this is more or less the equivalent of `pngcrush`: not much more than a wrapper around `flif` to try different encoding settings automatically, essentially treating the encoder as a black box with some parameters.

At some point, we can go further and make the FLIF equivalent of `pngout`, which in the case of PNGs implements an improved method to deflate, and in the case of "`flifout`" it could implement an improved MANIAC tree learning method.

And maybe later we can even have the FLIF equivalent of `zopflipng`, which would take an enormous amount of computational resources but would produce more or less the smallest possible .flif file for a given image.

Anyway, I'll fork this repo on FLIF-hub and give you push access :)
